<?php
/**
 * @author Ondrej Donek <ondrejd@gmail.com>
 * @link https://github.com/ondrejd/odwp-debug_log for the canonical source repository
 * @license https://www.gnu.org/licenses/gpl-3.0.en.html GNU General Public License 3.0
 * @package odwp-debug_log
 * @see DL_Log_Dashboard_Widget::init()
 * @since 1.0.0
 */

if( ! defined( 'ABSPATH' ) ) {
    exit;
}

if( ! class_exists( 'DL_Log_Table' ) ) {
    require_once( DL_PATH . 'src/DL_Log_Table.php' );
}

$dl_log_table = new DL_Log_Table();
$dl_log_table->prepare_items();

?>
<div class="wrap">
    <form method="post">
        <input type="hidden" name="page" value="ttest_list_table">
        <?php
            $dl_log_table->search_box( 'search', 'search_id' );
            $dl_log_table->display();
    ?></form>
</div>
