<?php
/**
 * ...
 */

if( ! defined( 'ABSPATH' ) ) {
    exit;
}

?>
<p>This is an example dashboard widget!</p>
<p>This is the front-facing part of the widget, and can be found and edited from <tt><?php echo __FILE__ ?></tt></p>
<p>Widgets can be configured as well. Currently, this is set to <strong><?php echo self::get_dashboard_widget_option( DL_Log_Dashboard_Widget::WID, DL_SLUG ); ?></strong> ! To change the number, hover over the widget title and click on the "Configure" link.</p>
