<?php
/**
 * @author Ondrej Donek <ondrejd@gmail.com>
 * @link https://github.com/ondrejd/odwp-debug_log for the canonical source repository
 * @license https://www.gnu.org/licenses/gpl-3.0.en.html GNU General Public License 3.0
 * @package odwp-debug_log
 * @see DL_Log_Table::extra_tablenav()
 * @since 1.0.0
 */

if( ! defined( 'ABSPATH' ) ) {
    exit;
}

?>
<div class="alignleft actions">
    <label for="filter_by_type" class="screen-reader-text"><?php _e( 'Filter by type', DL_SLUG ) ?></label>
    <select name="filter-by-type" id="filter_by_type" title="<?php _e( 'Filter by type', DL_SLUG ) ?>">
        <?php foreach( $type_filters as $val => $lbl ) : 
            printf( '<option value="%1$s" %2$s>%3$s</option>', $val, selected( $time, $val, false ), $lbl );
        endforeach ?>
    </select>
    <input name="<?php echo DL_SLUG . '-filter_submit' ?>" id="<?php echo DL_SLUG . '-filter_submit' ?>" class="button" value="<?php _e( 'Filter', DL_SLUG ) ?>" type="submit">
</div>
