<?php
/**
 * @author Ondřej Doněk <ondrejd@gmail.com>
 * @link https://github.com/ondrejd/odwp-debug_log for the canonical source repository
 * @license https://www.gnu.org/licenses/gpl-3.0.en.html GNU General Public License 3.0
 * @package odwp-debug_log
 * @see DL_Plugin::admin_menu()
 * @since 1.0.0
 */

if( ! defined( 'ABSPATH' ) ) {
    exit;
}

?>
<div class="wrap">
    <form action="options.php" method="post">
        <h1>
            <?php _e( 'Nastavení pro plugin Prohlížeč chybových zpráv', DL_SLUG ) ?>
        </h1>
    <?php
            settings_fields( DL_SLUG );
            do_settings_sections( DL_SLUG );
            submit_button();
    ?>
    </form>
</div>
