<?php
/**
 * @author Ondrej Donek <ondrejd@gmail.com>
 * @link https://github.com/ondrejd/odwp-debug_log for the canonical source repository
 * @license https://www.gnu.org/licenses/gpl-3.0.en.html GNU General Public License 3.0
 * @package odwp-debug_log
 * @see DL_Screen_Prototype::screen_options()
 * @since 1.0.0
 */

if( ! defined( 'ABSPATH' ) ) {
    exit;
}

if( ! class_exists( 'DL_Log_Table' ) ) {
    require_once( DL_PATH . 'src/DL_Log_Table.php' );
}

// Construct log table
$dl_log_table     = new DL_Log_Table();
$table_options    = $dl_log_table->get_options();
$all_columns      = $dl_log_table->get_columns();
$hidden_columns   = $dl_log_table->get_hidden_columns();
$hideable_columns = array_keys( $dl_log_table->get_hideable_columns() );

// Access all options directly
extract( $table_options );

?>
<div id="screen-options-wrap" class="hidden" aria-label="<?php _e( 'Screen Options Tab', DL_SLUG ) ?>">
    <form name="<?php echo $slug ?>-form" method="post" class="odwp-screen-options">
        <?php echo wp_nonce_field( -1, $slug . '-nonce', true, false); ?>
        <input type="hidden" name="screen_name" value="<?php echo $screen->id ?>">
        <fieldset>
            <legend><?php _e( 'Table screen options', DL_SLUG ) ?></legend>
            <ul>
                <li>
                    <label><?php _e( 'Displayed columns: ', DL_SLUG ) ?></label>
                    <?php foreach( $all_columns as $col_key => $col_label ) :
                        if( $col_key != 'cb' ) :
                            $checked = ! in_array( $col_key, $hidden_columns );
                            $disabled = ! in_array( $col_key, $hideable_columns );
                    ?>
                    <label for="<?php echo $slug ?>-log_table_col_<?php echo $col_key ?>" class="<?php echo $disabled ? 'disabled' : '' ?>">
                        <input type="checkbox" name="<?php echo $slug ?>-show_cols[<?php echo $col_key ?>]" id="<?php echo $slug ?>-log_table_col_<?php echo $col_key ?>"<?php checked( $checked ) ?> <?php disabled( $disabled ) ?>>
                        <?php echo $col_label ?>
                    </label>
                    <?php endif; endforeach ?>
                    <br><span class="description"> <?php _e( 'Gray items are displayed by default and can\'t hidden.', DL_SLUG ) ?></span>
                </li>
                <li>
                    <label for="<?php echo $slug ?>-number1">
                        <?php _e( 'Count of records per page: ', DL_SLUG ) ?>
                        <input type="number" name="<?php echo $slug ?>-per_page" id="<?php echo $slug ?>-number1" min="5" max="100" step="1" value="<?php echo $per_page ?>" class="short">
                    </label>
                </li>
                <li>
                    <label for="<?php echo $slug ?>-checkbox1" title="<?php _e( 'Show record type as an icon?', DL_SLUG ) ?>">
                        <input type="checkbox" name="<?php echo $slug ?>-show_icons" id="<?php echo $slug ?>-checkbox1"<?php checked( $show_icons ) ?>>
                        <?php _e( 'Check if you want to see record type as an icon not as a normal text.', DL_SLUG ) ?>
                    </label>
                </li>
                <li>
                    <label for="<?php echo $slug ?>-checkbox2" title="<?php _e( 'Create links to source files?', DL_SLUG ) ?>">
                        <input type="checkbox" name="<?php echo $slug ?>-show_links" id="<?php echo $slug ?>-checkbox2"<?php checked( $show_links ) ?>>
                        <?php _e( 'Check if you want to create links to source files where was error occured.', DL_SLUG ) ?>
                    </label>
                </li>
                <li>
                    <label for="<?php echo $slug ?>-checkbox4" title="<?php _e( 'Show source file names shortened?', DL_SLUG ) ?>">
                        <input type="checkbox" name="<?php echo $slug ?>-short_src_links" id="<?php echo $slug ?>-checkbox4"<?php checked( $short_src_links ) ?>>
                        <?php _e( 'Show source file names shortened (e.g. without absolute path <code>ABSPATH</code>)?', DL_SLUG ) ?>
                    </label>
                </li>
                <li>
                    <label for="<?php echo $slug ?>-checkbox3" title="<?php _e( 'Show stack trace defaultly unfolded?', DL_SLUG ) ?>">
                        <input type="checkbox" name="<?php echo $slug ?>-show_trace" id="<?php echo $slug ?>-checkbox3"<?php checked( $show_trace ) ?>>
                        <?php _e( 'Check if you want to have <em>stack trace</em> defaultly unfolded.', DL_SLUG ) ?>
                    </label>
                </li>
                <li>
                    <label for="<?php echo $slug ?>-number1">
                        <?php _e( 'Set width and height for the modal window with source codes.  Width: ', DL_SLUG ) ?>
                        <input type="number" name="<?php echo $slug ?>-src_win_width" id="<?php echo $slug ?>-number1" value="<?php echo $src_win_width ?>" min="480" max="2000" step="1">
                        <?php _e( ', height: ', DL_SLUG ) ?>
                        <input type="number" name="<?php echo $slug ?>-src_win_height" id="<?php echo $slug ?>-number2" value="<?php echo $src_win_height ?>" min="300" max="2000" step="1">
                    </label>
                    <br><span class="description"><?php _e( 'This option has effect only when creating source files links is enabled (see above).', DL_SLUG ) ?></span>
                </li>
                <li>
                    <label for="<?php echo $slug ?>-select1">
                        <?php _e( 'Set column which will be sorted by default ', DL_SLUG ) ?>
                        <select name="<?php echo $slug ?>-sort_col" id="<?php echo $slug ?>-select1" value="<?php echo $sort_col ?>">
                            <?php foreach( $dl_log_table->get_columns() as $col_key => $col_lbl ) :
                                if( $col_key != 'cb' ) :
                            ?>
                            <option value="<?php echo $col_key ?>"<?php selected( $col_key, $sort_col ) ?>><?php echo $col_lbl ?></option>
                            <?php endif; endforeach ?>
                        </select>
                        <?php _e( ' and its order ', DL_SLUG ) ?>
                        <select name="<?php echo $slug ?>-sort_dir" id="<?php echo $slug ?>-select2" value="<?php echo $sort_dir ?>">
                            <option value="asc"<?php selected( 'desc', $sort_dir ) ?>><?php _e( 'Ascendant', DL_SLUG ) ?></option>
                            <option value="desc"<?php selected( 'desc', $sort_dir ) ?>><?php _e( 'Descendant', DL_SLUG ) ?></option>
                        </select>
                    </label>
                </li>
            </ul>
        </fieldset>
        <p class="submit">
            <input type="submit" name="<?php echo $slug ?>-submit" value="<?php _e( 'Save settings', DL_SLUG ) ?>" class="button button-primary">
        </p>
    </form>
</div>
