<?php
/**
 * @author Ondřej Doněk <ondrejd@gmail.com>
 * @link https://github.com/ondrejd/odwp-debug_log for the canonical source repository
 * @license https://www.gnu.org/licenses/gpl-3.0.en.html GNU General Public License 3.0
 * @package odwp-debug_log
 * @see DL_Plugin::admin_menu()
 * @since 1.0.0
 */

if( ! defined( 'ABSPATH' ) ) {
    exit;
}

if( ! class_exists( 'DL_Log_Table' ) ) {
    require_once( DL_PATH . 'src/DL_Log_Table.php' );
}

$dl_log_table = new DL_Log_Table();
$dl_log_table->prepare_items();

?>
<div class="wrap">
    <h1><?php _e( 'Prohlížeč ladících informací', DL_LOG ) ?></h1>
    <div style="color: #f30;">
        <p><strong>TODO</strong> - dokončit stránku:</p>
        <ul style="list-style: square; padding-left: 20px;">
            <li>přidat sloupec s typem chyby (zobrazit jako ikonu) a hlavní text chyby o tento typ zkrátit (bude zkrácen jen, když je sloupec zobrazen)</li>
            <li>přidat filtrování - zobrazit jen dnešní chyby, chyby za poslední hodinu, zobrazit chyby určitého typu (<em>PHP Parse Error</em>, <em>PHP Warning</em>, <em>PHP Fatal Error</em>)</li>
            <li>dokončit hromadné úpravy (smazat vybrané záznamy)</li>
            <li>opravit/dokončit řazení dat</li>
            <li>umožnit proklik na zdrojové kódy ve kterých se chyba vyskytne</li>
            <li style="text-decoration: line-through;">přidat základní stránkování</li>
            <li>defaultní počet položek na stránce by měl být ovlivněn uživatelským nastavením</li>
            <li>umožnit uživateli nastavit, které sloupce se mají zobrazit</li>
            <li>vyřešit všechny problémy, které se mohou vyskytnout při použití na nástěnce (<em>dashboard widget</em>)</li>
        </ul>
    </div>
    <!-- <?php var_dump( $dl_log_table->items ); ?> -->
    <form method="post">
        <input type="hidden" name="page" value="ttest_list_table">
        <?php
            $dl_log_table->search_box( 'search', 'search_id' );
            $dl_log_table->display();
    ?></form>
</div>
