<?php
/**
 * @author Ondrej Donek <ondrejd@gmail.com>
 * @link https://github.com/ondrejd/odwp-debug_log for the canonical source repository
 * @license https://www.gnu.org/licenses/gpl-3.0.en.html GNU General Public License 3.0
 * @package odwp-debug_log
 * @see DL_Plugin::admin_menu()
 * @since 1.0.0
 */

if( ! defined( 'ABSPATH' ) ) {
    exit;
}

if( ! class_exists( 'DL_Log_Table' ) ) {
    require_once( DL_PATH . 'src/DL_Log_Table.php' );
}

/**
 * @var \DL_Log_Table $dl_log_table
 */
$dl_log_table = new DL_Log_Table();
$dl_log_table->prepare_items();

/**
 * Add ThickBox support.
 * @link https://developer.wordpress.org/reference/functions/add_thickbox/
 */
add_thickbox();
?>
<div class="wrap">
    <h1 class="wp-heading-inline"><?php _e( 'Debug Log Viewer', DL_SLUG ) ?></h1> <a class="page-title-action" href="#"><?php _e( 'Delete log', DL_SLUG ) ?></a>
    <span style="display: none"><?php _e( 'Small plugin aimed for developers that want easilly see their debug.log file.', DL_SLUG ) ?></span>
    <hr class="wp-header-end">
    <h2 class="screen-reader-text"><?php _e( 'Filter records', DL_SLUG ) ?></h2>
    <?php $dl_log_table->views() ?>
    <form id="odwpdl-log_table" method="get">
        <?php $dl_log_table->search_box( 'search', 'search_id' ) ?>
        <input type="hidden" name="page" value="<?php echo DL_Log_Screen::SLUG ?>">
        <?php /**
         * @todo Add hidden intput "_wpnonce"!
         * @todo Add hidden input "_wp_http_referer"!
         */ ?>
        <h2 class="screen-reader-text"><?php _e( 'Log records', DL_SLUG ) ?></h2>
        <?php $dl_log_table->display() ?>
    </form>
</div>
