<?php
/**
 * @author Ondrej Donek <ondrejd@gmail.com>
 * @link https://github.com/ondrejd/odwp-debug_log for the canonical source repository
 * @license https://www.gnu.org/licenses/gpl-3.0.en.html GNU General Public License 3.0
 * @package odwp-debug_log
 * @see DL_Plugin::admin_menu()
 * @since 1.0.0
 */

if ( ! defined( 'ABSPATH' ) ) {
    exit;
}

if ( ! class_exists( 'DL_Log_Table' ) ) {
    require_once( DL_PATH . 'src/DL_Log_Table.php' );
}

// TODO All screen actions should be implemented also via normal GET request not just Ajax!

// Show raw log action
$show_raw_log = filter_input( INPUT_GET, 'show_raw_log', FILTER_SANITIZE_NUMBER_INT );

// Set up screen actions URLs
$delete_log_action_base_url = add_query_arg( 'delete_log', '1', DL_Log_Table::get_current_url() );
$delete_log_action_url = wp_nonce_url( $delete_log_action_base_url, 'delete_log' );
$show_raw_log_action_url = add_query_arg( 'show_raw_log', '1', DL_Log_Table::get_current_url() );
$show_rich_log_action_url = DL_Log_Table::get_current_url();

?>
<div class="wrap">
    <h1 class="wp-heading-inline"><?php esc_html_e( 'Debug Log Viewer', DL_SLUG ) ?></h1>
    <a class="page-title-action odwpdl-screen_action-delete" href="<?php echo esc_url( $delete_log_action_url ) ?>"><?php esc_html_e( 'Delete log', DL_SLUG ) ?></a>
    <?php if ( $show_raw_log == '1' ) : ?>
    <a class="page-title-action odwpdl-screen_action-toggle_view odwpdl-screen_is_raw" href="<?php echo esc_url( $show_rich_log_action_url ) ?>"><?php esc_html_e( 'Show nice log', DL_SLUG ) ?></a>
    <?php else : ?>
    <a class="page-title-action odwpdl-screen_action-toggle_view odwpdl-screen_is_rich" href="<?php echo esc_url( $show_raw_log_action_url ) ?>"><?php esc_html_e( 'Show raw log', DL_SLUG ) ?></a>
    <?php endif ?>
    <hr class="wp-header-end">
    <?php if ( $show_raw_log == '1' ) :

        $log_raw = DL_Log_Parser::get_instance( DL_Log_Table::get_options() )->get_raw_log();

        // TODO Number of rows set via user/default settings!
        // TODO Move all inline styles to proper CSS file!
    ?><form>
        <p class="description"><?php printf(
                __( 'Here are untouched contents of %1$sdebug.log%2$s file. Its size is %3$s%5$s%4$s, total count of lines is %3$s%6$d%4$s.', DL_SLUG ),
                '<code>', '</code>', '<strong>', '</strong>',
                size_format( DL_Log_Parser::get_instance()->get_log_filesize() ),
                count( $log_raw )
        ) ?></p>
        <textarea class="odwpdl-log_raw" rows="27" disabled><?php
            // We use `DL_Log_Parser` as usual;
            echo join( '', $log_raw );
        ?></textarea>
    </form>
    <?php else :

        /**
         * @var \DL_Log_Table $dl_log_table
         */
        $dl_log_table = new DL_Log_Table();
        $dl_log_table->prepare_items();

        /**
         * Add ThickBox support.
         * @link https://developer.wordpress.org/reference/functions/add_thickbox/
         */
        add_thickbox();

    ?><h2 class="screen-reader-text"><?php esc_html_e( 'Filter records', DL_SLUG ) ?></h2>
    <?php $dl_log_table->views() ?>
    <form id="odwpdl-log_table" method="get">
        <input type="hidden" name="page" value="<?php echo DL_Log_Screen::SLUG ?>">
        <?php
        // TODO Add hidden intput "_wpnonce"!
        ?>
        <?php $dl_log_table->search_box( 'search', 'search_id' ) ?>
        <h2 class="screen-reader-text"><?php esc_html_e( 'Log records', DL_SLUG ) ?></h2>
        <?php $dl_log_table->display() ?>
    </form>
    <?php endif ?>
</div>
