<?php
/**
 * @author Ondřej Doněk <ondrejd@gmail.com>
 * @link https://github.com/ondrejd/odwp-debug_log for the canonical source repository
 * @license https://www.gnu.org/licenses/gpl-3.0.en.html GNU General Public License 3.0
 * @package odwp-debug_log
 * @see DL_Plugin::render_settings_section_2()
 * @since 1.0.0
 */

if( ! defined( 'ABSPATH' ) ) {
    exit;
}

?>
<p class="description">
    <?php _e( 'Níže můžete zadat obrázky, okraje a verše pro editor oznámení.', NG_SLUG ) ?>
</p>
