<?php
/**
 * @author Ondřej Doněk <ondrejd@gmail.com>
 * @link https://github.com/ondrejd/odwp-debug_log for the canonical source repository
 * @license https://www.gnu.org/licenses/gpl-3.0.en.html GNU General Public License 3.0
 * @package odwp-debug_log
 * @see DL_Plugin::render_setting_only_list_style()
 * @since 1.0.0
 *
 * Variables passed:
 * @var string $list_style ['default','short']
 */

if( ! defined( 'ABSPATH' ) ) {
    exit;
}

?>
<select id="<?php echo DL_SLUG ?>_settings_list_style" name="<?php echo DL_SLUG ?>_settings[list_style]" value="<?php echo $list_style ?>">
    <option value="default"<?php selected( $list_style, 'default' ) ?>><?php _e( 'Defaultní', DL_SLUG ) ?></option>
    <option value="short"<?php selected( $list_style, 'disabled' ) ?>><?php _e( 'Zkrácený', DL_SLUG ) ?></option>
</select>
<p class="description"><?php _e( 'Zobrazení výpisu chyb - můžete zvolit buď defaultní nebo zkrácený výpisu.', DL_SLUG ) ?></p>
