<?php
/**
 * @author Ondřej Doněk <ondrejd@gmail.com>
 * @link https://github.com/ondrejd/odwp-debug_log for the canonical source repository
 * @license https://www.gnu.org/licenses/gpl-3.0.en.html GNU General Public License 3.0
 * @package odwp-debug_log
 * @see DL_Plugin::render_setting_only_list_style()
 * @since 1.0.0
 *
 * Variables passed:
 * @var string $list_style ['default','short']
 */

if( ! defined( 'ABSPATH' ) ) {
    exit;
}

?>
<label for="odwpdl_settings_list_style">
    <select id="odwpdl_settings_list_style" name="odwpdl_settings[list_style]" value="<?php echo $list_style ?>">
        <option value="default"<?php selected( $debug_mode, 'default' ) ?>><?php _e( 'Defaultní', DL_SLUG ) ?></option>
        <option value="short"<?php selected( $debug_mode, 'disabled' ) ?>><?php _e( 'Zkrácený', DL_SLUG ) ?></option>
    </select>
    <?php _e( 'Typ zobrazení', NG_SLUG ) ?>
</label>
<p class="description"><?php _e( 'Zobrazení výpisu chyb - můžete zvolit buď defaultní nebo zkrácený výpisu.', NG_SLUG ) ?></p>
