<?php
/**
 * @author Ondřej Doněk <ondrejd@gmail.com>
 * @link https://github.com/ondrejd/odwp-debug_log for the canonical source repository
 * @license https://www.gnu.org/licenses/gpl-3.0.en.html GNU General Public License 3.0
 * @package odwp-debug_log
 * @see DL_Plugin::render_settings_section_1()
 * @since 1.0.0
 */

if( ! defined( 'ABSPATH' ) ) {
    exit;
}

?>
<p class="description">
    <?php _e( 'Pro ukládání chybových a ladících informací do souboru <code>debug.log</code> musí být vaše instalace <a href="https://wordpress.org/" target="blank">WordPress</a> nastavena - jedná se o jednoduchou úpravu souboru <code>wp-config.php</code>, kterou může tento plugin provést za vás, když povolíte ladící mód níže.', DL_SLUG ) ?>
</p>
