<?php
/**
 * @author Ondřej Doněk <ondrejd@gmail.com>
 * @link https://github.com/ondrejd/odwp-debug_log for the canonical source repository
 * @license https://www.gnu.org/licenses/gpl-3.0.en.html GNU General Public License 3.0
 * @package odwp-debug_log
 * @see DL_Plugin::render_setting_debug_mode()
 * @since 1.0.0
 *
 * Variables passed:
 * @var string $debug_mode ['enable','disable']
 */

if( ! defined( 'ABSPATH' ) ) {
    exit;
}

?>
<label for="odwpdl_settings_debug_mode">
    <select id="odwpdl_settings_debug_mode" name="odwpdl_settings[debug_mode]" value="<?php echo $debug_mode ?>">
        <option value="enabled"<?php selected( $debug_mode, 'enabled' ) ?>><?php _e( 'Povolit', DL_SLUG ) ?></option>
        <option value="disabled"<?php selected( $debug_mode, 'disabled' ) ?>><?php _e( 'Zakázat', DL_SLUG ) ?></option>
    </select>
    <?php _e( 'Povolit ladící mód', NG_SLUG ) ?>
</label>
<p class="description"><?php _e( 'Pokud ladící mód povolíte, budou se všechny chyby zapisovat do souboru <code>debug.log</code>.', NG_SLUG ) ?></p>
